### PR TITLE
Image source tests

### PR DESCRIPTION
**Pull request by bhousel**
This adds an image source to all raster-* tests

### CODE REVIEW

**Comment by mourner** [comment]
Why did you have to update all expected pics in this PR? They're not all affected by raster changes, right?

**Comment by bhousel** [comment]
The update command updates them all, and gl-js is the reference implementation, so why not?

**Comment by mourner** [comment]
@bhousel the updated images seem the same. I'm just wondering if we should avoid unnecessarily clogging the git repo (it grows bigger every time), or just update everything on every minor change. cc @jfirebaugh what do you think?

**Comment by jfirebaugh** [comment]
It's not a big deal, but yeah, I usually revert any non-material changes to `expected.png`s. They can have trivial differences depending on what machine they were generated on (even between different Macs).

**Comment by bhousel** [comment]
better?

**Comment by jfirebaugh** [comment]
Yes! Now I can see what actually changed.

Please make separate tests for `"raster"` vs `"image"` sources -- don't have layers using each source active at the same time. It's going to be a while before gl-native implements image sources and we want the existing raster tests to be usable in the interim.

**Comment by bhousel** [comment]
> Please make separate tests for "raster" vs "image" sources

Sure, do you have a preference how we organize them?

We now have:
`/render-tests/raster-opacity/`

So to split them out by source, maybe:
`/render-tests/image-source-raster-opacity/*`
`/render-tests/raster-source-raster-opacity/*`

Or another level of hierarchy?
`/render-tests/image/raster-opacity/*`
`/render-tests/raster/raster-opacity/*`

**Comment by jfirebaugh** [comment]
`render-tests/raster-opacity/image` -- i.e. add an `.image` class that hides the satellite layer and shows the image layer, and in `info.json` add

```
    "image": {
        ...,
        "classes": ["image"]
    }
```

**Comment by bhousel** [comment]
> i.e. add an .image class that hides the satellite layer and shows the image layer

Ok, kind of confused by this.. Classes don't really show and hide layers, they enable/disable paint properties.  Do you want me to duplicate the [code from the `raster-visibility` test](https://github.com/mapbox/mapbox-gl-test-suite/blob/master/render-tests/raster-visibility/style.json) into every other `raster-*` test?  

Even that raster-visibility test linked above - is it really testing visibility, or is it testing that the correct classes override the `"raster-opacity": 0` value?

**Comment by jfirebaugh** [comment]
The current test convention is to use `*-opacity` overrides to provide class-based visibility control. It's not ideal, but it has been working.

Now that we have `center`, `zoom`, etc properties in the style (and `metadata` as well), it would be better to eliminate `index.json` and class use and just have a separate style for each and every test case. But that's a bigger change.

Thinking again about my previous comment, I suspect the approach I suggested will actually still not work for gl-native -- I think it will fail as soon as a source of type `image` is introduced. How about instead adding additional cases to https://github.com/mapbox/mapbox-gl-test-suite/blob/master/render-tests/image/info.json, and we'll come back and do a larger refactoring later?

**Comment by bhousel** [comment]
> Now that we have center, zoom, etc properties in the style (and metadata as well), it would be better to eliminate index.json and class use and just have a separate style for each and every test case. But that's a bigger change.

I like this idea a lot!  I'm ticketing it separately.

I'll add the `raster-*` tests to `render-tests/image/info.json` for now..

**Comment by bhousel** [comment]
I think this is finished now.. @jfirebaugh?

**Comment by jfirebaugh** [comment]
:+1:

**Pull request merged**
