### PR TITLE
Add pitch test

### PR DESCRIPTION
**Pull request by bsudekum**
Adds tests for pitch. ref mapbox-gl-native pull: https://github.com/mapbox/mapbox-gl-native/pull/2702

/cc @jfirebaugh @mikemorris

### CODE REVIEW

**Comment by mikemorris** [comment]
:+1:

**Comment by jfirebaugh** [comment]
Testing different ways of setting `line-color` (default, constant, function) isn't valuable for this test. It would make more sense to test different pitch values instead.

**Comment by bsudekum** [comment]
@jfirebaugh good call. Updated to test:

* default, no pitch
* zero pitch
* 15 degree pitch
* 30 degree pitch

**Comment by jfirebaugh** [comment]
:+1:

**Comment by mikemorris** [comment]
Testing gl-js against https://github.com/mapbox/mapbox-gl-test-suite/pull/56, I'm noticing three of the `line-pitch` tests are failing (the only ones which set the pitch to a non-zero value). Has `pitch` been implemented in gl-js yet?

**Comment by bsudekum** [comment]
@mikemorris yes, pitch has been implemented in gl-js.

**Comment by mikemorris** [comment]
@bsudekum It was missing from https://github.com/mapbox/mapbox-gl-js/blob/master/test/render.test.js#L16-L31, adding it in my PR.

**Pull request merged**
