### PR TITLE
Fix query tests for v2 features

### PR DESCRIPTION
**Pull request by lucaswoj**
cc @jfirebaugh @ansis @jakepruitt @mapsam 

There are a number of tests that began failing after the v2 upgrade due to reliance on undefined behaviour. These tests fall into two categories:

# Failing Hidden Symbol Tests

These tests were relying on label placement. Changes in geometries, such as merging lines with identical properties, caused the label placement to shift enough to cause these tests to fail.

What the test was supposed to be

zuksgmbadddbswl7dzwlu7vn5el6g9 dh8mv4o676fbq pjrssjlivsld80r8pxwcn8b78dk83dhqcr7h8rx4or1ejn mtymllfkomp8pbnph20qfip8aaaaasuvork5cyii

What the test was after v2 upgrade

icyzvdcuruwaaaaasuvork5cyii

# Other Failing Tests

Many other tests were failing because they were querying the edge of rendered features, getting just enough of an antialiased pixel to return the expected results. 

wp skkqwr4rmgaaaabjru5erkjggg

# Bonus: `expected.json` Indentation

The `query-tests/*/*/expected.json` files now use 4 spaces for indentation, consistent with other JSON files in this repository.

### CODE REVIEW

**Comment by jfirebaugh** [comment]
2 space indent is actually the standard. That's what all render test `style.json`s use, due to it being [`gl-style-format`s default](https://github.com/mapbox/mapbox-gl-style-spec/blob/mb-pages/bin/gl-style-format).

**Comment by lucaswoj** [comment]
It looks like

 - `query-tests/*/*/style.json` use 4 spaces (but they should have been using two, this tripped me up)
 - `render-tests/*/*/style.json` use 2 spaces per `gl-style-format`

I'll add a commit to make sure 2 spaces are used everywhere.

**Comment by lucaswoj** [comment]
I pushed a commit that makes all JSON files now use 2-space indentation (and provides a utility format JSON files in the future).

**Comment by jfirebaugh** [comment]
👍 🚢

**Pull request merged**
