### PR TITLE
tests changes for reparsing overscaled tiles

### PR DESCRIPTION
**Pull request by ansis**
- line interpolation for labels and icons is different for overscaled tiles
- distance along line values change a tiny bit which shifts  dashes/images slightly
- layout property functions are recalculated at each zoom making the letter-spacing test change

### CODE REVIEW

**Comment by jfirebaugh** [comment]
We probably shouldn't have the tests testing overscaled tiles by default, which is what is happening now. Many tests are at z16 but use z14 tiles.

If we change such tests to render at z14 rather than z16, do the expected results still make decent test cases?

**Comment by jfirebaugh** [comment]
(We should have targeted overscaling tests for important properties too, of course.)

**Comment by ansis** [comment]
@jfirebaugh all z15/16 tests switched to z14 in 2f8ef25

**Comment by jfirebaugh** [comment]
:+1:

**Pull request merged**
