### PR TITLE
V2 fixtures

### PR DESCRIPTION
**Pull request by mikemorris**
Updated test fixtures to v2 vector tiles with the script below - some expected test results will need to be updated to match.
```
npm install mapnik@3.5.0
```
```
var fs = require('fs');
var mapnik = require('mapnik');
var args = process.argv.slice(2);

var file = args[0].split('.vector.pbf')[0];
var data = fs.readFileSync(file + '.vector.pbf');
var vtile = new mapnik.VectorTile(0,0,0);
vtile.setData(data);

fs.writeFileSync(file + '.mvt', vtile.getData());
```
```
find tiles/*.vector.pbf -exec node convert.js {} \;
```

### CODE REVIEW

**Comment by mikemorris** [comment]
Running `UPDATE=true npm run test-suite` in gl-js updated ~300 expected results - most look unchanged but a few are noticeably different. I'm assuming this should be expected with a switch in the underlying vector tiles AND the trianguation engine, but I'm unsure how to verify which changes are expected.

/cc @mourner @jfirebaugh

**Comment by mikemorris** [comment]
Examples of different expected results:

### debug/tile
**Old**

**New**


### extent/1024-fill
**Old**

**New**

**Comment by mourner** [comment]
> var vtile = new mapnik.VectorTile(0,0,0);

Are all fixtures 0-0-0? The tile number affects encoding, right?

**Comment by mikemorris** [comment]
@mourner from chat with @flippmoke:

> with a get/set your coordinates don’t matter either
so you can do any z,x,y
they [only] are if you do something with the data such as render it to an image
because that defines the geographic information about the tile
or if you did `vtile.toGeoJSON()` etc

**Comment by mikemorris** [comment]
Testing these updated fixtures in gl-native, I'm seeing three very minor test failures that all look like rounding errors in line dash-array/pattern placement - everything else is passing.

### line-dasharray/overscaled
**Expected** (gl-js)
2_old

**Actual** (gl-native)
2_new

### line-dasharray/slant
**Expected** (gl-js)
old1

**Actual** (gl-native)
new1

### line-pattern/overscaled
**Expected** (gl-js)
3_old

**Actual** (gl-native)
3_new

**Comment by lucaswoj** [comment]
Subsumed by #89

**Pull request closed without merging**
