### PR TITLE
Upgrade vector tile fixtures to v2 

### PR DESCRIPTION
**Pull request by lucaswoj**
We need to do this before we merge earcut in GL JS or else we will have rendering errors caused by using v1 tiles with earcut. Most of changes to `expected.png` images seem to be related to small positional differences causing bigger collision differences.

cc @springmeyer @mapsam @jfirebaugh @mourner @ansis

### CODE REVIEW

**Comment by lucaswoj** [comment]
## Author's Notes

 - the first commit is a whole lotta `.vector.pbf` -> `.mvt`
 - the second commit contains all `expected.png` image changes
    - `debug/collision` has been failing (but ignored) for months 
    - `extent/*` tests are now using source data based on mapbox-streets-v7 rather
    - `fill-outline-color/*` tests seem to be broken due to antialiasing changes -- this one's still a mystery to me
    -

**Comment by mapsam** [comment]
Uneducated question: are there tests that ensure warnings are thrown for v1 tiles? What's the behavior of Mapbox GL JS if it encounters a v1 tile?

**Comment by jfirebaugh** [comment]
How did you generate the new tiles with non-standard extent? Might be useful to have that process recorded for posterity.

**Comment by lucaswoj** [comment]
@mapsam I am in the process of implementing a warning (based on the value of the `version` field per https://github.com/mapbox/vector-tile-js)

@jfirebaugh The script I wrote to upgrade the tiles and generate the non-standard extent tile is [here](https://gist.github.com/lucaswoj/777d57f8ad0e33a02b5a92ce660c9683). Do you think it'd be appropriate to leave that in the `tiles` directory?

**Comment by jfirebaugh** [comment]
@lucaswoj Yeah, that'd be great.

**Comment by lucaswoj** [comment]
@jfirebaugh Just pushed upgrade script. 🚢?

**Comment by jfirebaugh** [comment]
:ship

**Pull request merged**
