### PR TITLE
Added tests for a raster layer with an alpha channel

### PR DESCRIPTION
**Pull request by lucaswoj**
Looks like headless-gl doesn't handle the alpha properly, even with the fix in https://github.com/mapbox/mapbox-gl-js/pull/1699. 

I propose we merge this as-is, merge https://github.com/mapbox/mapbox-gl-js/pull/1699, and revisit when a fix lands for headless-gl.

### CODE REVIEW

**Comment by lucaswoj** [comment]
cc @jfirebaugh @mourner @gribbet

**Comment by jfirebaugh** [comment]
Does it render correctly with both https://github.com/mapbox/mapbox-gl-js/pull/1699 and https://github.com/mapbox/mapbox-gl-js/tree/stacklgl-headless-gl-2?

**Comment by lucaswoj** [comment]
actual

It's _closer_ with `headless-gl-2`. Looks like one tile didn't get alpha blending applied but the rest did!

**Comment by lucaswoj** [comment]
Every time I run the suite, I get different results. 

actual

**Comment by gribbet** [comment]
The fix is incorrect. UNPACK_PREMULTIPLY_ALPHA_WEBGL needs to be set before the texImage2D call.

**Comment by gribbet** [comment]
The PR has been updated. 
@lucaswoj Could you try again with the new fix?

**Comment by lucaswoj** [comment]
Sure @gribbet

**Comment by lucaswoj** [comment]
The fix works! (with `headless-gl-2`).

**Comment by lucaswoj** [comment]
ref https://github.com/mapbox/mapbox-gl-js/issues/1447

**Pull request merged**
